name: main
on: [ push ]
jobs:
  test-e2e:
    name: 'E2E tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          start: yarn run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
          record: true
        env:
          CYPRESS_baseUrl: http://localhost:8080/
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  test-unit:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn install
      - run: yarn run test:unit
